/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant
    Soft IP Version: 1.1.0.3
    Tue Sep 11 16:45:38 2018
*******************************************************************************/
/*******************************************************************************
    Include IP core template files.
*******************************************************************************/
`include "core/lscc_compact_cnn_accelerator.v"
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module lsc_ml_ice40_cnn (clk, resetn, o_rd_rdy, i_start, i_we, i_waddr, i_din,
    o_we, o_dout, o_cycles, o_commands, o_fc_cycles, i_debug_rdy, o_debug_vld,
    o_fill, i_fifo_empty, i_fifo_low, o_fifo_rd, i_fifo_dout, o_status);
    input  clk;
    input  resetn;
    output  o_rd_rdy;
    input  i_start;
    input  i_we;
    input  [15:0]  i_waddr;
    input  [15:0]  i_din;
    output  o_we;
    output  [15:0]  o_dout;
    output  [31:0]  o_cycles;
    output  [31:0]  o_commands;
    output  [31:0]  o_fc_cycles;
    input  i_debug_rdy;
    output  o_debug_vld;
    output  o_fill;
    input  i_fifo_empty;
    input  i_fifo_low;
    output  o_fifo_rd;
    input  [31:0]  i_fifo_dout;
    output  [7:0]  o_status;
    lscc_compact_cnn_accelerator #(.ML_TYPE("CNN"),
        .MEM_TYPE("DUAL_SPRAM"),
        .BNN_ONEZERO(1),
        .SCRATCH_SIZE("1K"))
    lscc_compact_cnn_accelerator_inst(.clk(clk),
        .resetn(resetn),
        .o_rd_rdy(o_rd_rdy),
        .i_start(i_start),
        .i_we(i_we),
        .i_waddr(i_waddr),
        .i_din(i_din),
        .o_we(o_we),
        .o_dout(o_dout),
        .o_cycles(o_cycles),
        .o_commands(o_commands),
        .o_fc_cycles(o_fc_cycles),
        .i_debug_rdy(i_debug_rdy),
        .o_debug_vld(o_debug_vld),
        .o_fill(o_fill),
        .i_fifo_empty(i_fifo_empty),
        .i_fifo_low(i_fifo_low),
        .o_fifo_rd(o_fifo_rd),
        .i_fifo_dout(i_fifo_dout),
        .o_status(o_status));
endmodule