/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant Software (64-bit) 1.1.0.165.1
    Soft IP Version: 1.0.0
    Thu May 16 16:53:34 2019
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module rom_himax_cfg_1fps (rd_clk_i, rd_en_i, rd_clk_en_i, rd_addr_i,
    rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rd_clk_i;
    input  rd_en_i;
    input  rd_clk_en_i;
    input  [7:0]  rd_addr_i;
    output  [15:0]  rd_data_o;
endmodule