/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant
    Soft IP Version: 1.0.0
    Tue Oct 23 11:51:21 2018
*******************************************************************************/
/*******************************************************************************
    Include IP core template files.
*******************************************************************************/
`include "core/lscc_ram_dq.v"
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module rom_alphanumeric14 (clk_i, clk_en_i, wr_en_i, wr_data_i, addr_i,
    rd_data_o);
    input  clk_i;
    input  clk_en_i;
    input  wr_en_i;
    input  [15:0]  wr_data_i;
    input  [7:0]  addr_i;
    output  [15:0]  rd_data_o;
    lscc_ram_dq #(.ADDR_DEPTH(256),
        .DATA_WIDTH(16),
        .ADDR_WIDTH(8),
        .REGMODE("noreg"),
        .RESETMODE("sync"),
        .INIT_MODE("mem_file"),
        .INIT_FILE("misc/ram256x16_alphanumeric_rom_alphanumeric14_copy.mem"),
        .INIT_FILE_FORMAT("hex"))
    lscc_ram_dq_inst(.clk_i(clk_i),
        .rst_i(1'b0),
        .clk_en_i(clk_en_i),
        .rd_out_clk_en_i(1'b1),
        .wr_en_i(wr_en_i),
        .wr_data_i(wr_data_i),
        .addr_i(addr_i),
        .rd_data_o(rd_data_o));
endmodule